#!/bin/bash
# Make sure you have already installed nbgrader: https://nbgrader.readthedocs.io/en/stable/user_guide/installation.html

# Uncomment this for the first run:
# nbgrader quickstart nbgrader-notebooks

for i in ./notebooks/*.ipynb
do
   s=${i##*/}
   fname=${s%.ipynb}
   mkdir ./nbgrader-notebooks/source/$fname
   cp $i ./nbgrader-notebooks/source/$fname/$fname.ipynb
done

cd nbgrader-notebooks
for i in ./source/*
do
   nbgrader db assignment add ${i##*/}
   nbgrader assign ${i##*/}
done
